### ISSUE TITLE
`sodium_init()`. What's its role in JS?

### ISSUE THREAD

**Issue by BatikhSouri** [jedisct1/libsodium.js#1]
Hey,

I noticed that you called "commented in" the `libsodium_raw._sodium_init()` line in `wrap-template.js`. I was wondering if it is a necessary call in JS, since it's role in C is to open `/dev/urandom` on Unix-like systems and to keep it open.

**Comment by jedisct1** [comment]
`sodium_init()` generates a canary for allocation functions (not available in Javascript), opens `/dev/urandom` (not mandatory in Javascript especially since `chroot(2)` is not available), and picks architecture-specific implementations (useless in Javascript).
While it doesn't hurt to do it, you're right, it's actually not required in JS.

**Comment by BatikhSouri** [comment]
Actually, as I've seen up to now, calling `sodium_init()` does throw an exception. (So I was asking if it would hurt to remove it; and you answered my question).

**Comment by jedisct1** [comment]
For a good reason: random numbers generation doesn't work. I'm was looking at this as we speak.

**Comment by jedisct1** [comment]
Looks like the default random implementation is empty, and not `randombytes_sysrandom_implementation`. This doesn't happen in the executable test files, so maybe more symbols have to be exported for this to work.
