### ISSUE TITLE
What should be do when something cannot be decrypted/verified?

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/libsodium.js#117]
Looks like the library currently throws an exception when something cannot be decrypted, or when a signature cannot be verified.

The exception message is confusing, but that could be easily fixed.

But what should we do in such a situation? Is an exception what you would expect here?

Or return `null` instead?

**Comment by jedisct1** [comment]
[sodium-native](https://github.com/sodium-friends/sodium-native) takes the output buffer as an argument, and returns the error code. That's another option. Fairly consistent with the C library, but completely incompatible with the current API.

**Comment by buu700** [comment]
I think exceptions are the most logical way to handle these cases.

Returning a numerical status code is idiomatic in C, but would feel out of place in JavaScript IMO, and like you said isn't really trivial to retrofit onto the existing API anyway.

Returning null/undefined could work, but a bunch of existing code would need to be updated to handle that change, and I think it'd make error handling unnecessarily verbose since users would then need to continue handling exceptions while also adding an additional check for null return values.

**Comment by jedisct1** [comment]
Point taken.

Let's keep the exceptions, then, but make the message they contain more relevant.
