### ISSUE TITLE
sodium.min.js has broken asm code

### ISSUE THREAD

**Issue by buu700** [jedisct1/libsodium.js#13]
I get the following error on Firefox:

![sodiumasmerror](https://cloud.githubusercontent.com/assets/415435/7789784/399f47ba-023c-11e5-820f-a2148551bb44.png)

Not sure what the best way to fix it is, but this worked for me for now:

`line=$(($(grep -n 'return Module;' sodium.js | sed 's/:.*//g')+1))`  
`head -n $line sodium.js > sodium.min.js`  
`tail -n +$(($line+1)) sodium.js | uglifyjs --stats --mangle --compress sequences=true,dead_code=true,conditionals=true,booleans=true,unused=true,if_return=true,join_vars=true,drop_console=true >> sodium.min.js # uglifyjs args copied from Makefile`

**Comment by jedisct1** [comment]
Hi,

And thanks for reporting this!

The root cause seems to be UglifyJS changing

`x = x | 0` which is valid asm.js to `x |= 0` which is not.

Unfortunately, that's a pretty old issue in UglifyJS which doesn't seem to be solved yet: https://github.com/srijs/rusha/issues/27

That's pretty annoying. I guess a possible workaround would be to only use the Closure Compiler for the asm.js part, and keep uglifyjs for the wrapper.

**Comment by jedisct1** [comment]
Does 79e675404b0381850e6cd1aff066077b2c185180 fix your issue?

**Comment by buu700** [comment]
Awesome, yep, this gets rid of the error for me.
