### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by manishmalik** [jedisct1/libsodium.js#15]
I am getting ```AssertionError: Emscripten failed to generate .js: 
make: *** [libsodium/test/js.done] Error 1
```even when I compile without modifying any files. I have already intalled all the dependencies mentioned on your readme.

PS: http://pastebin.com/g0XVgmaf

**Comment by jedisct1** [comment]
Might be a bug in Emscripten. What version are you using?

**Comment by manishmalik** [comment]
I installed it using the `apt-get install emscripten` btw I am on ubuntu 14.04. Running `emcc -v` gives me the version as 
```
emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.10.0
Ubuntu clang version 3.3-16ubuntu1 (branches/release_33) (based on LLVM 3.3)
```
Is that what you want ? Or may be you could tell me on what emscripten version did you usually compile ? I will try it on that also.

**Comment by jedisct1** [comment]
Gosh, that's really old.

I compile the code using the standard Emscripten package in Homebrew. Currently `1.33.0`.

    emcc (Emscripten gcc/clang-like replacement) 1.33.0 (commit aa0c5b95e04617f0c5f398265cc0e474870b76a5)

Can you try with a more recent version?

**Comment by CryptoNoob** [comment]
It's dangerous to go alone!
Use this:
-------
[For ubuntu!  :D]
# Clone the repo
git clone https://github.com/jedisct1/libsodium.js.git
# Enter to the "root"
cd ./libsodium.js/libsodium/
# Set the paths to the new binaries/compilers
directory=`pwd`
export PATH="$PATH:$directory/emsdk:$directory/emsdk/clang/fastcomp/build_master_64/bin:$directory/emsdk/emscripten/master"
# Get and untar the new emsdk 
wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
tar -xzvf ./emsdk-portable.tar.gz
mv ./emsdk_portable ./emsdk
# Fetch the latest registry of available tools.
./emsdk/emsdk update
# Download and install the latest SDK tools.
./emsdk/emsdk install latest
# Make the "latest" SDK "active"
./emsdk/emsdk activate latest
# Set the current Emscripten path on Linux/Mac OS X
source ./emsdk/emsdk_env.sh
# Configure nodejs instead of node (Ubuntu don't have a binary called node, it have nodejs)
rm ~/.emscripten
echo "import os" >> ~/.emscripten
echo "SPIDERMONKEY_ENGINE = \"\"" >> ~/.emscripten
echo "NODE_JS = \"nodejs\"" >> ~/.emscripten
echo "LLVM_ROOT=\"$directory/emsdk/clang/fastcomp/build_master_64/bin\"" >> ~/.emscripten
echo "EMSCRIPTEN_ROOT=\"$directory/emsdk/emscripten/master\"" >> ~/.emscripten
echo "V8_ENGINE = \"\"" >> ~/.emscripten
echo "TEMP_DIR = \"/tmp\"" >> ~/.emscripten
echo "COMPILER_ENGINE = NODE_JS" >> ~/.emscripten
echo "JS_ENGINES = [NODE_JS]" >> ~/.emscripten
echo "" >> ~/.emscripten
# Return to the "parent"
cd ..
# Use the magic!  XD
make
------

Be happy and keep up the good work! ;)

**Comment by manishmalik** [comment]
Thanks! :) 
I will give it a try by the weekend and will let you know about it. 
Till then I am closing this issue.

**Comment by Jaaap** [comment]
> echo "NODE_JS = "nodejs"" >> ~/.emscripten
> echo "LLVM_ROOT="$directory/emsdk/clang/fastcomp/build_master_64/bin"" >> ~/.emscripten

Thanks @CryptoNoob your post really helped.
On my Ubuntu 18 box i had to change these 2 entries to:
```
echo "NODE_JS = "node"" >> ~/.emscripten
echo "LLVM_ROOT="$directory/emsdk/clang/e1.38.30_64bit"" >> ~/.emscripten
```
