### ISSUE TITLE
Feature request: crypto_stream_chacha20_xor_ic

### ISSUE THREAD

**Issue by CryptoNoob** [jedisct1/libsodium.js#19]
Hello Frank.

In our project we need the function "crypto_stream_chacha20_xor_ic" ported to JS,
so I have done the required code. :D 

I hope it is fine.

Thanks! :)

**Comment by CryptoNoob** [comment]
Hi Frank!
When you have the chance, please could you review the code and if it is OK accept the pull request in order to be able to use the library through bower.
Thanks and keep up the good work! :) 

CryptoNoob

**Comment by jedisct1** [comment]
Hi,

Unfortunately, adding just `crypto_stream_chacha20_xor_ic()` would make the project quite inconsistent.

This would probably require `crypto_stream_chacha20_xor()` first. Which would require `crypto_stream_chacha20()` beforehand. Which would require `crypto_stream()` beforehand, as well as a different build of the library (not the minimal build which is currently used for the JavaScript target).

In order to keep the API simple and accessible, low-level functions are intentionally not exposed by in the JavaScript version. If that has to change, we can't just add one specific function out of the blue; all of them have to be added, and maintained.

If you need this function, as you already figured it out, it's fairly easy to add the extra symbols you need to the `EXPORTED_FUNCTIONS` variable, and then add the JS high-level API.

But in the precompiled and supported JavaScript code, I'd rather stick to the high-level minimal API for now.

**Comment by bennyn** [comment]
@CryptoNoob: Have you found a solution to your problem? If yes, can you share your learnings? Would be really happy to see how to solve this problem. :smiley:

**Comment by gpalomar** [comment]
Hi @jedisct1 . According to your last comment answering @CryptoNoob , what are that functions?
[`crypto_stream_chacha20_xor_ic()`](https://download.libsodium.org/doc/advanced/chacha20.html)
[`crypto_stream_chacha20_xor()`](https://download.libsodium.org/doc/advanced/chacha20.html)
[`crypto_stream_chacha20()`](https://download.libsodium.org/doc/advanced/chacha20.html)
[`crypto_stream()`](https://download.libsodium.org/doc/advanced/xsalsa20.html)

There are more functions to write?
If I add these functions, will you accept a pull request?

**Comment by jedisct1** [comment]
If we want to expose low-level functions:

```
crypto_auth_hmacsha256
crypto_auth_hmacsha256_bytes
crypto_auth_hmacsha256_final
crypto_auth_hmacsha256_init
crypto_auth_hmacsha256_keybytes
crypto_auth_hmacsha256_statebytes
crypto_auth_hmacsha256_update
crypto_auth_hmacsha256_verify
crypto_auth_hmacsha512
crypto_auth_hmacsha512256
crypto_auth_hmacsha512256_bytes
crypto_auth_hmacsha512256_final
crypto_auth_hmacsha512256_init
crypto_auth_hmacsha512256_keybytes
crypto_auth_hmacsha512256_statebytes
crypto_auth_hmacsha512256_update
crypto_auth_hmacsha512256_verify
crypto_auth_hmacsha512_bytes
crypto_auth_hmacsha512_final
crypto_auth_hmacsha512_init
crypto_auth_hmacsha512_keybytes
crypto_auth_hmacsha512_statebytes
crypto_auth_hmacsha512_update
crypto_auth_hmacsha512_verify
crypto_box_curve25519xsalsa20poly1305
crypto_box_curve25519xsalsa20poly1305_afternm
crypto_box_curve25519xsalsa20poly1305_beforenm
crypto_box_curve25519xsalsa20poly1305_beforenmbytes
crypto_box_curve25519xsalsa20poly1305_boxzerobytes
crypto_box_curve25519xsalsa20poly1305_keypair
crypto_box_curve25519xsalsa20poly1305_macbytes
crypto_box_curve25519xsalsa20poly1305_noncebytes
crypto_box_curve25519xsalsa20poly1305_open
crypto_box_curve25519xsalsa20poly1305_open_afternm
crypto_box_curve25519xsalsa20poly1305_publickeybytes
crypto_box_curve25519xsalsa20poly1305_secretkeybytes
crypto_box_curve25519xsalsa20poly1305_seed_keypair
crypto_box_curve25519xsalsa20poly1305_seedbytes
crypto_box_curve25519xsalsa20poly1305_zerobytes
crypto_generichash_blake2b
crypto_generichash_blake2b_bytes
crypto_generichash_blake2b_bytes_max
crypto_generichash_blake2b_bytes_min
crypto_generichash_blake2b_final
crypto_generichash_blake2b_init
crypto_generichash_blake2b_init_salt_personal
crypto_generichash_blake2b_keybytes
crypto_generichash_blake2b_keybytes_max
crypto_generichash_blake2b_keybytes_min
crypto_generichash_blake2b_personalbytes
crypto_generichash_blake2b_salt_personal
crypto_generichash_blake2b_saltbytes
crypto_generichash_blake2b_update
crypto_hash_sha256
crypto_hash_sha256_bytes
crypto_hash_sha256_final
crypto_hash_sha256_init
crypto_hash_sha256_statebytes
crypto_hash_sha256_update
crypto_hash_sha512
crypto_hash_sha512_bytes
crypto_hash_sha512_final
crypto_hash_sha512_init
crypto_hash_sha512_statebytes
crypto_hash_sha512_update
crypto_onetimeauth_poly1305
crypto_onetimeauth_poly1305_bytes
crypto_onetimeauth_poly1305_final
crypto_onetimeauth_poly1305_init
crypto_onetimeauth_poly1305_keybytes
crypto_onetimeauth_poly1305_update
crypto_onetimeauth_poly1305_verify
crypto_onetimeauth_primitive
crypto_scalarmult_curve25519
crypto_scalarmult_curve25519_base
crypto_scalarmult_curve25519_bytes
crypto_scalarmult_curve25519_scalarbytes
crypto_secretbox_xsalsa20poly1305
crypto_secretbox_xsalsa20poly1305_boxzerobytes
crypto_secretbox_xsalsa20poly1305_keybytes
crypto_secretbox_xsalsa20poly1305_macbytes
crypto_secretbox_xsalsa20poly1305_noncebytes
crypto_secretbox_xsalsa20poly1305_open
crypto_secretbox_xsalsa20poly1305_zerobytes
crypto_shorthash_siphash24
crypto_shorthash_siphash24_bytes
crypto_shorthash_siphash24_keybytes
crypto_sign_ed25519
crypto_sign_ed25519_bytes
crypto_sign_ed25519_detached
crypto_sign_ed25519_keypair
crypto_sign_ed25519_open
crypto_sign_ed25519_publickeybytes
crypto_sign_ed25519_secretkeybytes
crypto_sign_ed25519_seed_keypair
crypto_sign_ed25519_seedbytes
crypto_sign_ed25519_sk_to_pk
crypto_sign_ed25519_sk_to_seed
crypto_sign_ed25519_verify_detached
crypto_stream_chacha20
crypto_stream_chacha20_ietf
crypto_stream_chacha20_ietf_noncebytes
crypto_stream_chacha20_ietf_xor
crypto_stream_chacha20_ietf_xor_ic
crypto_stream_chacha20_keybytes
crypto_stream_chacha20_noncebytes
crypto_stream_chacha20_xor
crypto_stream_chacha20_xor_ic
crypto_stream_keybytes
crypto_stream_noncebytes
crypto_stream_primitive
crypto_stream_salsa20
crypto_stream_salsa20_keybytes
crypto_stream_salsa20_noncebytes
crypto_stream_salsa20_xor
crypto_stream_salsa20_xor_ic
crypto_stream_xor
crypto_stream_xsalsa20
crypto_stream_xsalsa20_keybytes
crypto_stream_xsalsa20_noncebytes
crypto_stream_xsalsa20_xor
crypto_stream_xsalsa20_xor_ic
randombytes_salsa20_random
randombytes_salsa20_random_buf
randombytes_salsa20_random_close
randombytes_salsa20_random_stir
```

**Comment by fefafefa** [comment]
Hi libsodium.js fans! ;)

I am using "crypto_stream_chacha20_xor_ic()" to encrypt/decrypt by parts, because the web 
explorers don't like store big data files (2GB... more or less) on memory in order to work with 
them...

The question it is if I am doing well using this low_level function or, if they are a function on 
libsodium that can encrypt/decrypt by parts in order to avoid asking the web-browser to hold 
the entire file at the same time.

I know there are a high level function called "crypto_stream" that it is a stream cipher but, 
the method to encrypt/decrypt by parts it is not supported, or at least it is not trivial to split 
a file in two parts to load on memory, cipher with "crypto_stream" and don't reuse the 
nonces for example.

Maybe I am a little bit lost, sorry for that, but I want to create a secure Web-App and I think 
there is a functionality gab on the libsodium.js in order to do this easy and secure.

Thanks for this project and for all the replies! :D

Fefafefa

**Comment by bennyn** [comment]
In the company I work for we had to additionally expose `crypto_stream_chacha20_xor_ic` and `crypto_hash_sha256 `. We made a fork of libsodium.js and created our own release versions.

I would be happy if the functions mentioned would be part of the original libsodium.js so that we don't need to branch out.

**Comment by jedisct1** [comment]
You rarely want to use `crypto_stream*`. Split your content into smaller, fixed-size chunks, encrypt and authenticate them sequentially with `crypto_aead_chacha20poly1305_*`, `crypto_secretbox_*` or `crypto_box_*`.
Before the first chunk, send an encrypted header containing a subkey and a randomly chosen initial nonce. Then, encrypt each chunk, incrementing the nonce after each. The final chunk is the one with a valid authentication tag, but a size smaller than the chunk size. Or use the AD to tag the first, content and last blocks.

**Comment by gpalomar** [comment]
@fefafefa , that was what I meant! Thanks to @jedisct1 for your reply, this should be the solution.

**Comment by jedisct1** [comment]
Please note that the above protocol doesn't prevent an active attacker from replaying a previous ciphertext. In order to prevent this, the encrypted header must include something sent by the server. A traditional approach is to have the server send half of the nonce, have the client compute the other half, and use `server-half || client-half` as the nonce.
But at this point, you're quite reinventing TLS, which might not be a good idea.
