### ISSUE TITLE
crypto_pwhash differences

### ISSUE THREAD

**Issue by anonymoussprocket** [jedisct1/libsodium.js#190]
Hi, I updated from 054 to 074 and there seems to be differences in how `crypto_pwhash` behaves. 

In 054 the following two lines produce the same result. In 074 DEFAULT appears to be ARGON2I*D*13, calling the function with ARGON2I13 gives me `Error: invalid usage`.

`sodiumsumo.crypto_pwhash(sodiumsumo.crypto_box_SEEDBYTES, passphrase, salt, sodiumsumo.crypto_pwhash_OPSLIMIT_INTERACTIVE, sodiumsumo.crypto_pwhash_MEMLIMIT_INTERACTIVE, sodiumsumo.crypto_pwhash_ALG_ARGON2I13);`

`sodiumsumo.crypto_pwhash(sodiumsumo.crypto_box_SEEDBYTES, passphrase, salt, sodiumsumo.crypto_pwhash_OPSLIMIT_INTERACTIVE, sodiumsumo.crypto_pwhash_MEMLIMIT_INTERACTIVE, sodiumsumo.crypto_pwhash_ALG_DEFAULT);`

**Comment by jedisct1** [comment]
I have no idea what `054` and `074` refer to :) Can you explain where you got these numbers from?

`crypto_pwhash_ALG_DEFAULT` was never supposed to be equivalent to `crypto_pwhash_ARGON2I13`. 

It is (quoting the documentation) the currently recommended algorithm, which can change from one version of libsodium to another. 

`crypto_pwhash_OPSLIMIT_INTERACTIVE` and `crypto_pwhash_MEMLIMIT_INTERACTIVE` can also change.

You should store all the parameters, including the algorithm in order to produce the same stream later anyway. Your applications will automatically benefit from newer algorithms and safer parameters.

`crypto_pwhash_OPSLIMIT_INTERACTIVE` and `crypto_pwhash_MEMLIMIT_INTERACTIVE` are designed to be used with `crypto_pwhash_ALG_DEFAULT`.

If you explicitly need to use Argon2i, use `crypto_pwhash_ALG_ARGON2I13` along with the dedicated constants `crypto_pwhash_argon2i_OPSLIMIT_INTERACTIVE` and `crypto_pwhash_argon2i_MEMLIMIT_INTERACTIVE`.

**Comment by anonymoussprocket** [comment]
Thank you, that's what I needed. I was referring to libsodium-wrappers-sumo for nodejs and the differences between 0.5.4 and 0.7.4 versions of that library. The parameters were not being set explicitly, instead relying on "default" version of them. Everything works now.
