### ISSUE TITLE
minisign for JS releases?

### ISSUE THREAD

**Issue by maxogden** [jedisct1/libsodium.js#203]
Hi, I couldn't find the .js distribution files in any of the zips on https://download.libsodium.org/libsodium/releases/, would it be possible to include the `libsodium/libsodium-js` folder in future releases?

**Comment by jedisct1** [comment]
`download.libsodium.org` has only the library, not wrappers for other languages maintained independently.

Releases can be downloaded on GitHub: https://github.com/jedisct1/libsodium.js/releases

Webassembly/WASI builds will eventually be available for download on `libsodium.org`, but although these packages are built already, it's a bit too early to commit to supporting these because the WASI specification is still a moving target.
