### ISSUE TITLE
side-channel attacks

### ISSUE THREAD

**Issue by timkuijsten** [jedisct1/libsodium.js#21]
When reading the papers about NaCl there are some strong statements about preventing timing attacks by not branching based on input data, doing constant time comparisons etc. [1]. There are some concerns about the inability to guarantee time safety in high-level languages like JavaScript [2][3] so I wonder how can libsodium.js guarantee to be safe from these side-channel attacks like the original NaCl C/C++ versions? It looks like the original emscripten authors don't even know what side-channels are when asked about it [4].

[1] http://cr.yp.to/highspeed/coolnacl-20120725.pdf p8 "No data flow from secrets to load addresses", "No data flow from secrets to branch conditions"
[2] https://news.ycombinator.com/item?id=704689
[3] https://github.com/WhisperSystems/TextSecure-Browser/issues/41#issuecomment-47292950
[4] https://twitter.com/kripken/status/490335241471422466

**Comment by timkuijsten** [comment]
js-nacl has the same uncertainty https://github.com/tonyg/js-nacl/issues/30

**Comment by jedisct1** [comment]
Hi Tim,

The asm.js code is almost a transliteration of the LLVM IR code, with one major change: there are no 64-bit integers in Javascript, so any operation involving `i64` values (which Sodium uses quite a lot) is emulated by Emscripten. 

Fortunately, it turns out that Emscripten's functions to emulate operations on 64-bit values used by Sodium do not use conditional jumps or lookups at all. With one exception: bit shifts. But the condition depends on the number of bits to shift, not on the value, and sodium doesn't have any code shifting bits by a non-constant number.

There are no obvious surprises in the resulting code, including in critical functions such as `sodium_memcmp()`.

Now, the major issue with a JIT compiler is that it's hardly deterministic. It can go way beyond what LTO would have done. It would be totally correct for a Javascript VM to turn `h(k1, m)` and `h(k2, m)` into two different codes paths.

So, we cannot guarantee that there are no side-channels that could be exploited. And even if we could prove that there are none, for any given program and any data, it wouldn't hold true for very long.

For this reason, if you are using server-side Javascript, I would highly recommend using bindings for the native library instead of the pure Javascript implementation.

Client-side, you need to carefully evaluate the practical risks vs the benefits. Beyond timing attacks in a crypto library, simple operations such as converting a string to an array of bytes is likely to be a non-constant time operation as well.

**Comment by timkuijsten** [comment]
Hi Frank,

Thank you for this very informative answer. I will stick to your advice of using the bindings where possible (server-side). Is my thought right that only WebCrypto might be able to provide the guarantees that are needed, apart from the fact that it might take a while before all needed primitives are supplied, if ever [[1]](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25839).
