### ISSUE TITLE
Wrong test for unsigned int

### ISSUE THREAD

**Issue by svvac** [jedisct1/libsodium.js#266]
https://github.com/jedisct1/libsodium.js/blob/88928899b6289ff1a519235fb434ce3d6bd98f68/wrapper/macros/input_uint.js#L5-L6

The wrappers use the construct `(x | 0) === x` to check if a value has a fractional part. However, binary operations [first cast the value as a 32 bit signed int](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_OR) prior to the computation, effectively capping the usable values to `2^31 - 1`.

I don't know if that's the case everywhere, but at least in some places this test is guarding an input type of `uint64_t` (e.g. the `keyid` of `crypto_kdf_derive_from_key()`).

Barring bigints (which I have no idea how to interface here), javascript cannot safely represent 64bit integers, though it handles integers up to `Number.MAX_SAFE_INTEGER = 0x001f ffff ffff ffff`.

**Comment by jedisct1** [comment]
This is intentional. I don't trust all the function bindings to correctly handle values >= 2^32.

Looks like `crypto_kdf_derive_from_key()` does but in the original code, there were hard-coded `0` values everywhere for the top half of 64-bit values. I probably fixed some, not sure about what's left.

The right thing to do would be to check that every function. If the situation looks sane, we can indeed extend the check to accept values up to 2^53.

**Comment by svvac** [comment]
Do you mean checking the signatures for `uint64_t`, or something more subtle?

**Comment by jedisct1** [comment]
Checking that calls to functions accepting `unsigned long long`, `size_t` and `uint64_t` handle both halves of these values and not  just the lower half. These are encoded as two parameters in the emscripten ABI.
