### ISSUE TITLE
crypto_box_easy invalid output on some platforms

### ISSUE THREAD

**Issue by buu700** [jedisct1/libsodium.js#28]
Isolated test case: http://codepen.io/anon/pen/PqgQyy

I can't say exactly what conditions cause this issue (our production error emails indicate a variety of devices and browsers, including Firefox and Chrome), but I've been able to reliably reproduce it in iOS 7 on BrowserStack (though, oddly, not in iOS 7 on my local iOS simulator).

My first suspicion was endianness, but [this pen](http://codepen.io/anon/pen/pJBPrX) indicates that that isn't the case (both my machine and BS iOS 7 are little-endian).

---

Expected: bba64986e249af9642dd0067f6248857cb12cfb848

<img width="1227" alt="screen shot 2015-08-13 at 11 56 53 am" src="https://cloud.githubusercontent.com/assets/415435/9258808/726e5ae4-41b2-11e5-9e60-33c2e69db599.png">

Actual: 78001e42c8b9a6e3ebe953dbd73681fc4edce12e92

<img width="1051" alt="screen shot 2015-08-13 at 11 54 55 am" src="https://cloud.githubusercontent.com/assets/415435/9258812/754e2fe6-41b2-11e5-8ae3-ede49a371f15.png">

**Comment by buu700** [comment]
Hmm, is it possible that playing with emscripten/LLVM flags could resolve this?

On the off chance it's potentially helpful, I'll just throw out there that `emcc -O3 --llvm-opts 0` has been working pretty well for [ntru.js](https://github.com/cyph/ntru.js).

**Comment by jedisct1** [comment]
Hi, and thanks for spotting this!

Unfortunately, even compiling without any optimizations doesn't seem to work around this bug. I tried `-O2`, `-O0`, `--llvm-opts 0` and disabling LTO; it didn't make any difference.

And then, my Browserstack trial ran out :(

Anyway, we need to pinpoint the specific code that JSCore fails to interpret correctly.
`crypto_scalarmult()` would be my first suspect.

Since you apparently have access to the wonderful Browserstack, can you check if `crypto_scalarmult()` produces the expected results on iOS 7?

**Comment by buu700** [comment]
Yep, looks that's it. For [this pen](http://codepen.io/anon/pen/GJLdEq), my Chrome prints bca421aafaf76cda869e0385f439a81eec0e2114918cbbee895efb476e569f00 and BS iOS prints a3702e5469f1b89ea1d2226b8afade847b5795d72495478a238fb4bbc95c4951.

Also, in case it's helpful, I went ahead and temporarily granted you access to our BrowserStack account.

**Comment by jedisct1** [comment]
Hi Ryan,

I spent the day on this, to no avail. JavaScriptCore is utterly broken on iOS 7.

When a pure returns different results according to the number of times it is called, we have a problem.

When `-5358208381844 >> 12` and ``-5358208381844 / 12 + 1` evaluates to `-0`, things are getting really bad.

When performing a multiplication on a copy of a constant value doesn't yield the same result as doing it on the value, it's quite puzzling.

I can rewrite functions until it eventually works, but this are likely to break after every single change to the  original library. There's also very likely to be more to fix than the DH function.

It's lame, but at this point, I am going to give up and document iOS < 8 as unsupported.

**Comment by buu700** [comment]
Oooh, yeah, that sounds really bad. If that's the case, I'll just go ahead and drop support as well. Thanks for spending so much time on this!

**Comment by buu700** [comment]
Sorry, probably shouldn't close this if you're going to commit readme updates against it.

**Comment by jedisct1** [comment]
A compatibility list has been added: https://github.com/jedisct1/libsodium.js#compatibility

I feel pretty bad for having to give up, but the situation turned out to be worse than expected :(

On the bright side, iOS 8 adoption is pretty strong, iOS 9 is round the corner and iOS 7 users might soon become statistically less significant.
