### ISSUE TITLE
[Question] javascript web workers

### ISSUE THREAD

**Issue by ekodo** [jedisct1/libsodium.js#46]
Is there a way to use libsodium.js inside a web worker securely?

Because the web worker does not have access to `window.crypto.getRandomValues`
It would be nice if i could pass the entropy from the main window to the worker, or the worker just can ask the main window for some entropy.

**Update**
eg: https://github.com/wltsmrz/sjcl-webworker-instructive

**Comment by jedisct1** [comment]
Hi @ekodo ,

That's exactly the plan: have workers post a request to the main thread, and get back the random bytes.
Unfortunately that hasn't been implemented yet.
Nothing that cannot be worked around, but the fact that the API now becomes asynchronous complicates things a little bit.

**Comment by ekodo** [comment]
Okay, but for now there is now way (without an update to libsodium/libsodium.js) to use it?
Like you said: a workaround or something

**Comment by jedisct1** [comment]
Unfortunately not. But pull requests to make it happen would be very welcome!

**Comment by ekodo** [comment]
The asynchronous is really a problem. Do you have any hint, how you would start?
I'am not sure if this possible without a entropy cache or something else?

**Comment by PythonNut** [comment]
Is a RNG needed for all operations? I understand it being required for the generation of nonces and salts, but for functions like `crypto_pwhash` (with a salt that is generated ahead of time on the main thread), it should be fine to operate without a RNG, right?

**Comment by jedisct1** [comment]
If the module properly loads, it means that the library has been properly initialized and can work as expected.

"depending on the context, only some functions may work, and even functions documented as always successful may now throw an exception under some conditions" would not really inspire confidence.

**Comment by PythonNut** [comment]
Sounds like a lot of things referenced in the [sjcl web worker issue](https://github.com/bitwiseshiftleft/sjcl/issues/91) are relevant here as well. Namely, we may just be able to use `self.crypto.getRandomValues` in the workers according to [Mozilla's spec](https://developer.mozilla.org/en-US/docs/Web/API/RandomSource).

**Comment by jedisct1** [comment]
Oh, the `crypto` namespace being exposed in the webworker global scope is great!

I don't know what the status is for other browsers, but yes, at least for Firefox, we can definitely use that.

**Comment by jedisct1** [comment]
Just noticed that this is already what the current code is doing :)

This works fine on Chrome and Opera, but apparently not yet on Firefox nor Safari.

**Comment by BurningEnlightenment** [comment]
> This works fine on Chrome and Opera, but apparently not yet on Firefox nor Safari.

According to [Mozilla Bug Report 842818](https://bugzilla.mozilla.org/show_bug.cgi?id=842818) it should work on Firefox now, too.

**Comment by jedisct1** [comment]
That's pretty exciting! Thanks for the heads up!

**Comment by buu700** [comment]
I'm a little late to this thread, but I have a polyfill that I've been using in production for almost a year that I wouldn't mind contributing under a permissive license (if there's still any interest, given recent browser releases adding support for crypto in workers): https://github.com/cyph/cyph/blob/master/shared/js/cyph/crypto/web-crypto-polyfill.ts

It just needs a 32-byte seed from the main thread's `crypto.getRandomValues`, which is then used with `sodium.crypto_stream_chacha20` to provide a normal synchronous crypto API ([example usage](https://github.com/cyph/cyph/blob/884f4ee/shared/js/cyph/thread.ts#L94)).

**Comment by buu700** [comment]
I'm using it in a worker in @cyph. We've had a lot of issues in the past with things breaking in mysterious ways in Edge (and Safari), particularly in relation to workers, so I wouldn't have been surprised to find an issue here, but I just tested in Edge 16 in BrowserStack and everything works with no issues.

That said, a quick google search found this: [support Web Crypto API inside a Web Worker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7607496). We're still using the polyfill I linked in my last comment here, which would probably be why we aren't having any issues. (That's pretty lucky; I'm honestly surprised that it's still useful for anything more than supporting ancient versions of Firefox.)

Sounds like there's a bug in `.ready` since I would expect it to reject when `crypto` support doesn't exist, which I'll need to fix when I get a chance, but does using my polyfill fix the problem for you? (Compiled version attached.)

[web-crypto-polyfill.js](https://github.com/jedisct1/libsodium.js/files/1783206/web-crypto-polyfill.js.txt)

**Comment by webmaster128** [comment]
The libsodium-based web-crypto-polyfill seems to work, great!

However, since I do not need randomness in my Worker, I created a dummy RNG that produces static bytes for the initialization only. This avoids circular dependencies and the need to seed the worker RNG. If anyone is interested, see https://gist.github.com/webmaster128/694f75a9c51750250ba388811c3a6d88. Note: this fakes a RNG, which may have serious security implications. Use with caution!
