### ISSUE TITLE
Getting Error with Browserify

### ISSUE THREAD

**Issue by bezreyhan** [jedisct1/libsodium.js#6]
I created an empty main.js file with this in it:

```var sodium = require('libsodium-wrappers');```

I then browserified it: 

```browserify main.js -o bundle.js```

After loading bundle.js into my html and loading that page I received this error in the console:

```Uncaught TypeError: Cannot read property 'write' of undefined```

It's coming from this call:
```
process.stderr.write(a+\n")
```

Though, it works fine with bower.

**Comment by jedisct1** [comment]
Indeed, Browserify defines a minimal `process` object, and because this object is defined, Emscripten thinks it's running iojs/node and assumes that `stdout` and `stderr` are available as well.

I initially thought that Emscripten and Browserify were just not made to play with each other.

But 036d349a9dd8f588b74e50c26c10957453a1c264 should fix it. Not super clean, but it should do the trick.

Give me some time to do some testing and if everything looks fine, I'll update the npm package shortly after.

**Comment by jedisct1** [comment]
Looks like it's working :+1:

**Comment by jedisct1** [comment]
npm package updated.

**Comment by bezreyhan** [comment]
@jedisct1 works for me. Thanks for the quick fix!
