### ISSUE TITLE
Feature request: explicit error message for crypto_sign_open

### ISSUE THREAD

**Issue by yan-foto** [jedisct1/libsodium.js#72]
| Name | Version |
|-------|---------|
| `libsodium-wrappers` | `0.3.1` |
| Node.js | `v4.4.6` |

If for any reason `crypto_sign_open` fails with an error, there is absolutely no way to find out if the open procedure failed because the data didn't match (if it's the case, why a [non-zero value wasn't returned](https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html)) or if something internal caused the error. In the latter case, I would suggest to throw an error with an explicit message (which is not happening [here](https://github.com/jedisct1/libsodium.js/blob/master/dist/modules/libsodium-wrappers.js#L3079)).

**Comment by pdefreitas** [comment]
+1

**Comment by jedisct1** [comment]
What internal error are you referring to, and how would you change the API to do that without introducing vulnerabilities?

**Comment by pdefreitas** [comment]
I think that instead of returning raw content you could create a specific object pair and fill it with values like function return (value that usually is passed by reference) and result code (value that the function usually returns). That would require refactoring but it would actually help finding out why a function call is failing.

**Comment by jedisct1** [comment]
It's Friday night so I'm having difficulties grasping even things, even if originally clearly explained :)

Could you provide some sample test code that currently returns a single error code, but should return different ones?

What would the new prototypes of some random functions, such as `crypto_aead_chacha20poly1305_ietf_encrypt_detached()`, `crypto_generichash_init()`, `crypto_sign_ed25519_sk_to_seed()` and `sodium_version_string()`?

Giving details about why an operation such as a MAC or signature verification failed is dangerous. If this information is not transformed by the application as a unique and opaque error, it can lead to security disasters. See what happened with SSL and RSA padding oracles.

If `crypto_sign_open()` returns an error because of a small order R, this is not something we want to disclose. Ditto for degenerate X25519 public keys. That shouldn't happen, but if it does, we don't want to disclose this information and present it as a generic error instead. Just like login/password authentication forms do not disclose which element of the pair is wrong when the tuple doesn't validate. 

Being close to the original C API is also useful. It makes the transition from C to JS and back less confusing than different APIs.

**Comment by yan-foto** [comment]
It's been such a long time that I cannot even remember the exact situation that lead me to opening this feature request.

> If crypto_sign_open() returns an error because of a small order R, this is not something we want to disclose.

I agree with that when it comes to disclosing that information to the user. But wouldn't it make sense to have some kind of explicit errors for the developer? At the end, I found the error by debugging the whole code. I could've spared the whole debugging if I'd got some explicit errors.

I must also add, that I'm a novice when it comes to security! 🙇
