### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by stwiname** [jedisct1/libsodium.js#86]
Is there any reason this would not work in React Native?

It uses JavaScriptCore which is the same as what Mobile Safari uses.

**Comment by jedisct1** [comment]
If I understand properly, you tried to use the library within React Native and it "didn't work"?

If that is the case, what exactly "doesn't work"?

**Comment by stwiname** [comment]
I am trying to use the sumo version. When React-Native packages the it tries to require "fs", "path" and "crypto" but none of those modules exist in React-Native. I have just tried shimming those modules and it seems to run as if it is in a Node environment

**Comment by jedisct1** [comment]
So, it thinks that it's running in a Node environment?

The detection actually happens in the compiled Emscripten code, so you may want to open an issue in the Emscripten project instead.

**Comment by jedisct1** [comment]
Defining `Module["ENVIRONMENT"]="WEB"` may also work around this.

**Comment by bufke** [comment]
I actually know a bit about this, though I'm using NativeScript it's very similar. The JS environment here is not node so any node based strategy won't work. It's also not a browser with a dom and thus does not have window.crypto. "fs" and "path"  I *think* can be polyfilled easily. crypto is much harder. There are two possible strategies that I know of.

One is to use a webview so that you have access to the browser crypto.  https://www.npmjs.com/package/react-native-webview-crypto
This project attempts to "polyfill" crypto by using a bridge to a hidden webview. If that sounds crazy, it is. We had it work in proof of concept. libsodium.js uses crypto just for random values (I think) since we can't generate randomness in pure js.

The other option is to just use libsodium (not js) for android/ios and write wrappers back to js. I'm pretty sure react native lets you do this. It's far more time intensive and requires learning the whole stack of how to get libsodium running in mobile and how to communicate from JS. I think this way would ultimately be better.

I'd love to hear if you have success. We are only in the proof of concept mode for these ideas.

**Comment by stwiname** [comment]
We ended up using this for a short term solution. https://github.com/mvayngrib/react-native-crypto.

We will shift to using native code when we get the chance.

**Comment by vikeri** [comment]
@stwiname I'm also interested in libsodium for React Native, what is your best solution atm?

**Comment by bufke** [comment]
I have things working in nativescript using libsodium-jni for Android. It should work exactly the same for react native, I have to assume RN also supports referencing native code in js. I wrote about it [here](http://davidmburke.com/2017/06/20/using-libsodium-in-android-and-nativescript/)

The same general method should work in ios too. 

I thought about making a general libsodium js native wrapper. I actually have my own [libsodium wrapper](https://gitlab.com/burke-software/simple-asymmetric-js) and I did the nativescript specific work there (how many wrappers are in use at this point :smile:)

I thought about making a new project that reimplements libsodium.js wrapper functions. @jedisct1 how are the js wrapper functions made? I see them in /dist but I assume that is generated code? I would need to have those js wrapper functions just call Java/Obj-C libsodium C wrappers instead of asm.js libsodium. I'd also have to figure out how to convert Java (and later Obj-C) byte arrays to js u8intArray and back, it's probably doable - they are just arrays of numbers really. So many wrappers here...but writing C like Java code in JS is pretty fun.

**Comment by stwiname** [comment]
@vikeri I ended up contributing to this package with the methods that I needed. https://github.com/lyubo/react-native-sodium

**Comment by bufke** [comment]
That's really interesting @stwiname 

My current (unfinished) method looks like this

```
public static javaByteArrayToUint8Array(javaBytes: native.Array<number>) {
    let out = new Uint8Array(javaBytes.length);
    for (let i = 0; i < javaBytes.length; i++) {
      out[i] = javaBytes[i];
    }
    return out;
  }

  public static randombytes_buf(length: number): Uint8Array {
    let rand = new org.libsodium.jni.crypto.Random().randomBytes(length);
    return this.javaByteArrayToUint8Array(rand);
  }
```

That array conversion would be bad for performance but it means I could offer API compatibility with libsodium.js.  Looks like RN and NS native code access is quite a bit different though.

**Comment by vikeri** [comment]
@stwiname Yeah I also went with that library. It's been working well so far despite the dodgyness of not being on npm or appearing to be actively maintained.

**Comment by bufke** [comment]
Posting my completed project for anyone searching for this https://gitlab.com/burke-software/nativescript-libsodium I tried to maintain compatibility with libsodium.js wrappers to make it easier for hybrid apps (web + mobile app). For RN you could use the same method I did or use react-native-sodium posted above.

**Comment by tasn** [comment]
I created a small library to emulate the node crypto API (only `randomBytes()` and `createHash('sha1')`). It uses the new `expo-random`.
It's very raw, but it got `node-rsa` to work without ejecting. Maybe useful for this one too...

**Comment by Arlen22** [comment]
> So, it thinks that it's running in a Node environment?
> 
> The detection actually happens in the compiled Emscripten code, so you may want to open an issue in the Emscripten project instead.

Where does this happen? I don't see how I can work around this but how does it know if it's in the browser?
