### ISSUE TITLE
Misssing "crypto_sign_ed25519_sk_to_pk"

### ISSUE THREAD

**Issue by tux3** [jedisct1/libsodium.js#92]
It seems as if the wrapper is exposing it, but it's missing at runtime.

**Comment by jedisct1** [comment]
Since this is not part of the high-level API, it is not present in minimal builds, only in sumo builds.

[This file](https://github.com/jedisct1/libsodium/blob/master/dist-build/emscripten-symbols.def) defines what functions are exported in each version.

**Comment by tux3** [comment]
Thanks for the clarification.

This is confusing because `crypto_scalarmult_base` is in the minimal build. 
As a result I'm able to compute the public key from the private key for X25519 keypairs, but not for Ed25519!

**Comment by jedisct1** [comment]
`crypto_scalarmult` is a high-level API. It doesn't depend on a specific algorithm.

`crypto_sign_ed25519_*` is only defined for a very specific primitive. There are no guarantees that a public key can efficiently be computed from only the secret key with other primitives that might be added later. It can also be dangerous to use if the secret key is not correctly created for the given primitive.

However, `crypto_seed_keypair()` is a high-level API, available in all builds. So maybe this is something you can consider instead.

**Comment by Edwardzyc** [comment]
Might as well ask here instead of opening another issue

If I grab the sumo build, I can use the function - that part I get. Is it really unsafe/dangerous to use? crypto_sign_ed25519_sk_to_pk seems like a very convenient function to get the public key from the secret key

Is there an irc channel where people hangout for libsodium support/discussion?

Where is the documentation for crypto_seed_keypair()?
